# Generated by Django 5.2.4 on 2025-07-13 08:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=20)),
                ('plan_price', models.IntegerField()),
                ('plan_type', models.CharField(max_length=20)),
                ('plan_period', models.CharField(max_length=20)),
                ('is_Active', models.BooleanField(default=True)),
                ('Num_Devices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(blank=True, default='client', max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=2)),
                ('floors', models.CharField(max_length=10)),
                ('rooms', models.IntegerField()),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billgeneration',
            fields=[
                ('billdate', models.DateTimeField(auto_now_add=True)),
                ('billamount', models.IntegerField()),
                ('billstatus', models.CharField(max_length=20)),
                ('billgendate', models.DateTimeField(auto_now_add=True)),
                ('paymentid', models.CharField(blank=True, max_length=20, null=True)),
                ('InvoiceNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('billgeneratedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_generated', to=settings.AUTH_USER_MODEL)),
                ('billgeneratedfor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_received', to=settings.AUTH_USER_MODEL)),
                ('billgeneratedforplan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.internetplan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentdate', models.DateTimeField(auto_now_add=True)),
                ('paymentamount', models.IntegerField()),
                ('paymentstatus', models.CharField(max_length=20)),
                ('paymentmode', models.CharField(max_length=20)),
                ('collectedby', models.CharField()),
                ('paymentfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('paymentforbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.billgeneration')),
                ('paymentforplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.internetplan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('profpic', models.ImageField(blank=True, default='profile_pics/default_profile.webp', null=True, upload_to='profile_pics')),
                ('is_billable', models.BooleanField(default=True)),
                ('profile_comp', models.BooleanField(default=False)),
                ('buildingid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.building')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('ticketdate', models.DateTimeField(auto_now_add=True)),
                ('ticketstatus', models.CharField(max_length=20)),
                ('ticketsub', models.CharField(max_length=100)),
                ('priority', models.CharField(default='Low', max_length=20)),
                ('ticketdesc', models.CharField(max_length=100)),
                ('ticketupdate', models.DateField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('raised', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WifiCodeUpload',
            fields=[
                ('codeupid', models.AutoField(primary_key=True, serialize=False)),
                ('uploadeddate', models.DateTimeField(auto_now_add=True)),
                ('uploadstatus', models.CharField(default='Initiated', max_length=20)),
                ('uploadedto', models.FileField(upload_to='wifi_codes')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_wifi_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodePoool',
            fields=[
                ('codeid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('assigneddate', models.DateTimeField(blank=True, null=True)),
                ('deactivated', models.DateField(blank=True, null=True)),
                ('assignedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_codes', to=settings.AUTH_USER_MODEL)),
                ('sourcepdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.wificodeupload')),
            ],
        ),
    ]
