# Generated by Django 5.2.4 on 2025-07-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='coagent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='builing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='common.building'),
        ),
    ]
