# Generated by Django 5.2.4 on 2025-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketing',
            options={'ordering': ['-ticketdate']},
        ),
        migrations.AlterModelOptions(
            name='ticketupdates',
            options={'ordering': ['ticketupdate'], 'verbose_name_plural': 'Ticket Updates'},
        ),
        migrations.RemoveField(
            model_name='ticketupdates',
            name='id',
        ),
        migrations.AddField(
            model_name='ticketupdates',
            name='updateid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
