# Generated by Django 5.2.4 on 2025-07-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='client', max_length=100, null=True),
        ),
    ]
