# Generated by Django 5.2.4 on 2025-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepoool',
            name='device',
        ),
        migrations.AddField(
            model_name='codepoool',
            name='exiprydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
