# Generated by Django 5.2.4 on 2025-07-31 18:42

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=common.models.generate_payment_id, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
