# Generated by Django 5.2.4 on 2025-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='Collection Agent', max_length=100, null=True),
        ),
    ]
