# Generated by Django 5.2.4 on 2025-07-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='online_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
