# Generated by Django 5.2.4 on 2025-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customuser_role_alter_profile_builing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='owner', max_length=100, null=True),
        ),
    ]
