# Generated by Django 5.2.4 on 2025-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codepoool_device_codepoool_exiprydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoool',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
