# Generated by Django 5.2.4 on 2025-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_codepoool_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='planstatus',
            field=models.BooleanField(default=True),
        ),
    ]
