# Generated by Django 5.2.4 on 2025-07-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_payment_online_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='InvoiceId',
        ),
    ]
