# Generated by Django 5.2.4 on 2025-08-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_payment_id_payment_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoool',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='common.payment'),
        ),
    ]
