# Generated by Django 5.2.4 on 2025-08-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_codepoool_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='next_billdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_start_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='planenddate',
        ),
    ]
